name: Packer Build workflow

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed


jobs:
  jobs1:
    if: github.event.pull_request.merged == true
    name: Building custom image
    runs-on: ubuntu-latest
    env:
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      PKR_VAR_project_id: ${{secrets.PROJECT_ID}}
      PKR_VAR_source_image_family: ${{secrets.SOURCE_IMAGE_FAMILY}}
      PKR_VAR_zone: ${{secrets.IMAGE_ZONE}}
      PKR_VAR_ssh_username: ${{secrets.SSH_USERNAME}}
      PKR_VAR_network: ${{secrets.IMAGE_NETWORK}}
      PKR_VAR_image_name: ${{secrets.IMAGE_NAME}}
      PKR_VAR_image_description: ${{secrets.IMAGE_DESCRIPTION}}
      PKR_VAR_service_account_email: ${{secrets.SERVICE_ACCOUNT_EMAIL}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
      - name: Build with Maven
        run:  |
          sudo touch /var/log/webapp.log
          sudo chmod 755 /var/log/webapp.log
          mvn -B package --file pom.xml

      - name: GCP Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Run packer init
        working-directory: ./packer
        run: packer init .

      - name: Run Packer fmt
        working-directory: ./packer
        run: packer fmt -check .

      - name: Run packer validate
        working-directory: ./packer
        run: packer validate .

      - name: Run packer build
        working-directory: ./packer
        run: packer build .