name: Integration Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    name: Integration Testing
    runs-on: ubuntu-latest
    env:
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
      - name: Preparing log directory
        run: |
          sudo chmod -R 766 /var/log/
      - name: Running integration tests
        run: |
          mvn test --file pom.xml