name: Java Compiling with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    name: Compiling the web project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compiling with Maven
        run: mvn compile --file pom.xml
