name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Tesing maven file
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: csye
      DATABASE_USERNAME: ${{DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{DATABASE_PASSWORD}}
      DATABASE_URL: ${{DATABASE_URL}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD
      - name: Build with Maven
        run: mvn -B package --file pom.xml